### ISSUE TITLE
EXCEPTION: TypeError: this.warnings is undefined when localStorage disabled

### ISSUE THREAD

**Issue by srudenko** [phenomnomnominal/angular-2-local-storage#15]
Firefox: 49.0
After localStorage gets disabled in Firefox (about:config > dom.storage.enabled set to false)
Exception occurs:

`ORIGINAL EXCEPTION: TypeError: this.warnings is undefined
ORIGINAL STACKTRACE:
LocalStorageService.prototype.get@http://localhost:5000/build/webdeps/angular-2-local-storage/LocalStorageService.js:85:13`

**Comment by elwynelwyn** [comment]
Thanks for the report and PR, this is merged now, closing.
