### ISSUE TITLE
Error on compiling with angular 2

### ISSUE THREAD

**Issue by arthursp** [phenomnomnominal/angular-2-local-storage#22]
`get _LocalStorageService_75():import44.LocalStorageService {
    if ((this.__LocalStorageService_75 == (null as any))) { (this.__LocalStorageService_75 = new import44.LocalStorageService()); }
    return this.__LocalStorageService_75;
  }`

ngc : Error : [ts] Supplied parameters do not match any signature of call target.
constructor LocalStorageService(config: ILocalStorageServiceConfig): import44.LocalStorageService

**Comment by orestisioakeimidis** [comment]
I am getting the same error when using the AoT compiler. Please fix.

**Comment by yandreiy** [comment]
+1

**Comment by elwynelwyn** [comment]
I've just published `angular-2-local-storage@0.0.25` which fixes the issue.
Thanks for the bug report!

**Comment by elwynelwyn** [comment]
Aight, 0.0.25 definitely did not fix AoT...

I've refactored and got it all working, but it involved breaking changes, so I've bumped a major version.
Install `angular-2-local-storage@1.0.0` and it's good to go. Be sure to check out the updated usage notes.
