### ISSUE TITLE
es6 shim causing ts compilation error

### ISSUE THREAD

**Issue by paladinu** [phenomnomnominal/angular-2-local-storage#25]
Getting this error as a conflict between the es6 shim and core-js.

\node_modules\@types\core-js\index.d.ts(21,14): error TS2300: Build:Duplicate identifier 'PropertyKey'.
\wwwroot\modules\angular-2-local-storage\typings\globals\es6-shim\index.d.ts(3,14): error TS2300: Build:Duplicate identifier 'PropertyKey'.

I've tried putting all manner of things in my ts.config exclude section but can't seem to get past this.  Any ideas?  Should the shim really be in there anyway?

**Comment by elwynelwyn** [comment]
I have pushed a new release that removes the use of ES6-shim completely (using the TypeScript `lib` compiler option instead).

Try the new version @paladinu, and if you are still having issues feel free to reopen this issue!

**Comment by paladinu** [comment]
Thanks!  I'll give it a shot.
