### ISSUE TITLE
How to use it in the template ?

### ISSUE THREAD

**Issue by kenp77** [phenomnomnominal/angular-2-local-storage#26]
Hi,

How to store a value from an input text and then retrieve it in the component ? 

ex :  `<input type="text" [(ngModel)]="number">` 

And in my component do something like this : `@LocalStorageService() public number:number`

It will be nice to put a complete example

**Comment by elwynelwyn** [comment]
There is no build in decorator like that (although it's a pretty cool idea!), you will need to manually use the `localStorageService` to persist your data. One way to do that, using getters/setters:

    import { LocalStorageService } from 'angular-2-local-storage';
    
    const MY_COOL_STORAGE_KEY = 'wow';
    @Component({...})
    class MyCoolComponent {
        constructor (private localStorageService: LocalStorageService) {
        }

        private _myCoolNumber: number;
        public get myCoolNumber (): number {
            if (this._myCoolNumber === undefined) {
                this._myCoolNumber = this.localStorageService.get(MY_COOL_STORAGE_KEY);
            }
            return this._myCoolNumber;
        }

        public set myCoolNumber (newValue) {
            this._myCoolNumber = newValue;
            this.localStorageService.set(MY_COOL_STORAGE_KEY, newValue);
        }
    }

And then in your template bind to it as normal: `<input type="text" [(ngModel)]="myCoolNumber">`

This library aims to be a drop-in port of the existing angular-local-storage library, for people who have existing codebases they are migrating over to Angular 2.
As such, the usage of this library is pretty much the same as the usage of the original Angular 1 library - you can check out their docs here:
https://github.com/grevory/angular-local-storage

**Comment by kenp77** [comment]
Thank you for the reply. Is it normal that the myCoolNumber() function is called 12 times when i load the page ? I put a console.log to see what happens and the console.log output 12 times !

**Comment by elwynelwyn** [comment]
It depends on what is using the property you have created. It's quite normal for it to fire multiple times (12 does seem quite high but it could be that many depending on what your application is doing).
