### ISSUE TITLE
ClearAll functionality

### ISSUE THREAD

**Issue by eestein** [phenomnomnominal/angular-2-local-storage#28]
Hi, I read you use most of the code from angular-local-storage, but this method `clearAll` there has an optional parameter, the regex.

On angular-2-local-storage I'm obliged to inform the regex. My question is, if I do something like this `this.localStorageService.clearAll('');` will it work the same way or you validate/require a regex for removal? If that's the case, do you plan on implementing that functionality?

Thanks!

**Comment by elwynelwyn** [comment]
Hi @eestein, good spotting, this is an issue with our TypeScript interface.
I have fixed it (made the parameter optional as it should be) and published the new version @0.0.23
