### ISSUE TITLE
How to use the observables

### ISSUE THREAD

**Issue by CodePoetPro** [phenomnomnominal/angular-2-local-storage#31]
this.localStorage.setItems$.subscribe(
        ()=>this.router.navigate(["/dashboard"])
);

**Comment by sagie212** [comment]
**app.module.ts**
```
LocalStorageModule.withConfig({
            prefix: 'my-app',
            storageType: 'localStorage',
            notifyOptions : {setItem: true, removeItem:true}
        })
```
**component.ts**

`import {ILocalStorageEvent} from "angular-2-local-storage/dist/local-storage-events.interface";
`
```
this.localStorageService.setItems$.subscribe(function (e:ILocalStorageEvent) {
            console.log(e)
        });
```

**Comment by elwynelwyn** [comment]
It's probably better not to import the interface from the full path, and instead do:
`import { ILocalStorageEvent } from "angular-2-local-storage";`

That way if the folder structure changes in the future it will not break your code.
Everything "public" that you might need to import should be exported directly from the main `index.ts` file of the project so you can import it without specifying the path.
