### ISSUE TITLE
Cannot find `Provider` and `provide`

### ISSUE THREAD

**Issue by iamdevlinph** [phenomnomnominal/angular-2-local-storage#4]
```
import { Component } from '@angular/core';
import { Platform, ionicBootstrap } from 'ionic-angular';
import { StatusBar } from 'ionic-native';
import { LocalStorageService, LOCAL_STORAGE_SERVICE_CONFIG } from 'angular-2-local-storage';

// Create config options (see ILocalStorageServiceConfigOptions) for deets:
let localStorageServiceConfig = {
    prefix: 'my-app',
    storageType: 'sessionStorage'
};
// Provide the config to the service:
const LOCAL_STORAGE_CONFIG_PROVIDER: Provider = provide(LOCAL_STORAGE_SERVICE_CONFIG, {
    useValue: localStorageServiceConfig
});

// Use the provider:
ionicBootstrap(MyApp, [LocalStorageService, LOCAL_STORAGE_CONFIG_PROVIDER]);
```

TypeScript error: app/app.ts(29,38): Error TS2304: Cannot find name 'Provider'.
TypeScript error: app/app.ts(29,49): Error TS2304: Cannot find name 'provide'.

**Comment by phenomnomnominal** [comment]
Hi! When asking for help online, it'd be nice if you would offer a bit more than a lump of code and some error messages - which I'm assuming you already Googled and didn't find anything about. A bit of context goes a long way in terms of people's willingness and capability to help.

That said, this is a pretty simple thing to fix, and has nothing to do with this library. You need to import the two missing "names". They both live within the "core" module, so if you update your code to this...

```
import { Component, Provider, provide } from '@angular/core';
```

then it should work.
