### ISSUE TITLE
Angular 4 migration/support

### ISSUE THREAD

**Issue by HarelM** [phenomnomnominal/angular-2-local-storage#42]
I'm not sure if this is a problem with my code or this repository but I tried to use it with angular 4 and it failed (don't have the error message right now, can try it again if needed).
Are you aware of any limitations that will prevent this code from running with angular 4?

**Comment by phenomnomnominal** [comment]
We've been using it with Angular 4 with no issues. The error would be helpful 😄

**Comment by HarelM** [comment]
Sorry, I used a different package, all the local storage packages names are confusing (Google should really start owning it).
