### ISSUE TITLE
Probably need to check config for null

### ISSUE THREAD

**Issue by sharok** [phenomnomnominal/angular-2-local-storage#46]
I have a case when I need to create service with help of `Injector`.
```this.injector.get(LocalStorageService);```

Now, I get exception.

> zone.js:643 Unhandled Promise rejection: Cannot read property 'notifyOptions' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'notifyOptions' of undefined
>     at new LocalStorageService (local-storage.service.js:34)

@phenomnomnominal  Could you check please. I don't want to switch to another local storage service

**Comment by phenomnomnominal** [comment]
Hi @sharok 

The `config` is actually injected, so as long as you have provided something, then you should still be able to use the injector like that.

e.g. like this:

```
{ provide: 'LOCAL_STORAGE_SERVICE_CONFIG', useValue: userConfig }
```

Hope that helps.
