### ISSUE TITLE
TypeError: (intermediate value).share is not a function

### ISSUE THREAD

**Issue by rodrigoreal** [phenomnomnominal/angular-2-local-storage#51]
I'm getting this error after i update to angular 5: `ERROR TypeError: (intermediate value).share is not a function
    at new LocalStorageService (local-storage.service.js:45)`

The error is at this line: `this.errors$ = new Observable_1.Observable(function (observer) { return _this.errors = observer; }).share();`

Anyone have any idea why it is happening?

**Comment by phenomnomnominal** [comment]
Hi there, this has nothing to do with this library, but it looks like you haven't imported the `share` operator:

`import 'rxjs/add/operator/share';`
