### ISSUE TITLE
Update to angular 7

### ISSUE THREAD

**Issue by marriskleinert** [phenomnomnominal/angular-2-local-storage#61]
While it appears to be working correctly, the version compatibility should be updated.

**Comment by proggeramlug** [comment]
Push - would like to see this too!

**Comment by VVKot** [comment]
package.json is updated already. @phenomnomnominal @mattlewis92 Can you publish updated version to npm? Or there is some work in progress that you want to complete before?

**Comment by Benno007** [comment]
Would be great to have this updated 👍

**Comment by phenomnomnominal** [comment]
2.0.0 with the updates was published, which should have fixed it. I'm also pushing a 3.0.0 which changes the `withConfig` to `forRoot` to bring it in line with conventions, and also adds `providedIn: 'root'` to the service, so it can be used *without* configuring it.
