### ISSUE TITLE
Change/Release notes for 3.x

### ISSUE THREAD

**Issue by alignsoft** [phenomnomnominal/angular-2-local-storage#64]
I see there's a 3.0.1 release available via npm, and it's red-flagged as a major release with potentially breaking changes, but I can't find any release notes to know what's in this release, what may break (if anything), and where the test points are.

Am I looking in the wrong place, or are there release notes still coming?

Thanks!

**Comment by phenomnomnominal** [comment]
What got flagged? This was a very small change, just a null check fix essentially.

**Comment by alignsoft** [comment]
Because it's a major version update (v2.x to v3.x) it gets marked by VSCode as ' "<red>" : Major Update backward-incompatible updates', which doesn't always mean that, but I always check the release notes for breaking changes and that's when I realized there weren't any.

**Comment by phenomnomnominal** [comment]
Ah, sorry, I thought you meant 3.0.0 -> 3.0.1

Here's the commit: https://github.com/phenomnomnominal/angular-2-local-storage/commit/d9bf9310868fc11c23b0a154729e439bc9fd3a01

I haven't really put much love into this repo as we haven't been using it for a long time. If you'd like to help maintain it, I'm more than happy to get help.

**Comment by alignsoft** [comment]
Great - thanks! I'd be happy to help, but I'm not sure I could add much value to the project.
