### ISSUE TITLE
Wrong source mapping url

### ISSUE THREAD

**Issue by sunshineo** [phenomnomnominal/angular-2-local-storage#8]
In your index.js you have
```
//# sourceMappingURL=../../dist/index.js.map
```

This is wrong. After install, there is no dist folder

All you need is ./index.js.map
This also apply to all other js files created.

**Comment by phenomnomnominal** [comment]
Just fixed this now. `npm install angular-2-local-storage@latest` and you should be good to go.

**Comment by sunshineo** [comment]
Hello. This is not fixed. I installed 0.0.19 . You still have an extra "../" in the sourceMappingURL

**Comment by phenomnomnominal** [comment]
Does it work in 0.0.18?

**Comment by sunshineo** [comment]
@phenomnomnominal It works very well in 0.0.18 👍 
So regression.

**Comment by phenomnomnominal** [comment]
Gah. Sorry, as you can see this isn't really getting any attention. I threw it together and haven't touched the project that needs it since - soon it will be less shit 😅 

PRs accepted

**Comment by kordianbruck** [comment]
@sunshineo can be closed as well.
